# Generated by Django 3.1.3 on 2020-11-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0002_auto_20201106_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('Music Video', 'Music Video'), ('Documentary', 'Documentary'), ('News', 'News'), ('Entertainement', 'Entertainement'), ('Unspecified', 'Unspecified')], default='Unspecified', max_length=14),
        ),
    ]
